name: Build Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: techno-tango

      - name: Run Lint
        run: npm run lint
        working-directory: techno-tango

      - name: Build
        run: npm run build
        working-directory: techno-tango

      - name: Run tests
        run: npm run test -- --no-watch --browsers=ChromeHeadless
        working-directory: techno-tango
